---
- name: Check if Homebrew is installed
  stat: path=/usr/local/bin/brew
  register: homebrew_check

- name: Install Homebrew
  shell: 'echo "\r" | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  sudo: no
  when: not homebrew_check.stat.exists

- name: Install packages
  homebrew:
    update_homebrew=yes
    upgrade_all=yes
    name={{ item }}
    state=latest
  sudo: no
  with_items: osxs_packages

- name: Enable or disable OS X Server services
  osx_serveradmin: name={{ item.name }} state={{ item.state }}
  with_items: osxs_service_state

- name: Set user defaults
  # command: defaults write /Library/Preferences/com.apple.alf.plist globalstate -int 1
  # osx_defaults: domain=/Library/Preferences/com.apple.alf.plist key=globalstate type=int value=1
  osx_defaults:
    domain={{ item.domain }}
    key={{ item.key }}
    type={{ item.type }}
    value="{{ item.value }}"
  sudo: no
  with_items: osxs_user_defaults
  tags: test

- name: Set system
  osx_defaults:
    domain={{ item.domain }}
    key={{ item.key }}
    type={{ item.type }}
    value="{{ item.value }}"
  with_items: osxs_system_defaults
  tags: test

- name: Setup sudo for admin group
  lineinfile: >
    state=present
    backup=yes
    dest=/etc/sudoers
    regexp='^%admin'
    line='%admin ALL=(ALL) NOPASSWD: ALL'

- name: Copy /etc/issue
  copy:
    src=issue
    dest=/etc/issue
    owner=root
    group=wheel
    mode=0644

- name: Configure ssh
  template:
    backup=yes
    src=sshd_config.j2
    dest=/etc/sshd_config
    owner=root
    group=wheel
    mode=0644

- name: Make directory for ansible files
  file:
    dest=/etc/ansible
    state=directory
    owner=root
    group=wheel
    mode=0700

- name: Copy serveradmin settings file
  template:
    src=serveradmin_settings.j2
    dest={{ osxs_config_directory}}/serveradmin_settings
    owner=root
    group=wheel
    mode=0600
  notify:
    - apply settings
    - reload services

- name: Copy systemsetup.sh script
  template:
    src=systemsetup.sh.j2
    dest={{ osxs_config_directory }}/systemsetup.sh
    owner=root
    group=wheel
    mode=0700
  notify: run systemsetup.sh

- name: Copy networksetup.sh script
  template:
    src=networksetup.sh.j2
    dest={{ osxs_config_directory }}/networksetup.sh
    owner=root
    group=wheel
    mode=0700
  notify: run networksetup.sh

- name: Set hostname
  osx_changeip: name={{ osxs_fqdn }}
  notify: reboot
