---
- name: Check if homebrew is installed
  stat: path=/usr/local/bin/brew
  register: homebrew_check

- name: Install Homebrew
  shell: 'echo "\r" | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  sudo: no
  when: not homebrew_check.stat.exists

- name: Install packages
  homebrew: update_homebrew=yes upgrade_all=yes name={{ item }} state=latest
  sudo: no
  with_items: osxs_packages

- name: Setup system
  command: /usr/sbin/systemsetup -set{{ item.key }} {{ item.value.arg }}
  with_dict: osxs_systemsetup

- name: Configure server services
  command: /Applications/Server.app/Contents/ServerRoot/usr/sbin/serveradmin {{ item.value.arg }} {{ item.key }}
  with_dict: osxs_serveradmin

# - name: Firewall rules

- name: Setup sudo for admin group
  lineinfile: "state=present backup=yes dest=/etc/sudoers regexp='^%admin' line='%admin  ALL=(ALL) NOPASSWD: ALL'"

- name: Copy /etc/issue
  copy: src=issue dest=/etc/issue owner=root group=wheel mode=0644

- name: Configure ssh
  template: backup=yes src=sshd_config.j2 dest=/etc/sshd_config owner=root group=wheel mode=0644
  notify: restart ssh
