---
- name: apply settings
  shell: serveradmin settings < /etc/serveradmin_settings

- name: reload services
  shell: serveradmin stop {{ item }}; serveradmin start {{ item }}
  with_items: osxs_service_state.name

- name: run networksetup
  command: /etc/networksetup
