---
- name: apply settings
  shell: serveradmin settings < {{ macos_srvr_config_directory }}/serveradmin_settings

- name: reload services
  shell: serveradmin stop {{ item.name }}; serveradmin start {{ item.name }}
  with_items: macos_srvr_service_state
  when: item.state != 'stopped'

- name: run systemsetup.sh
  command: "{{ macos_srvr_config_directory }}/systemsetup.sh"

- name: run networksetup.sh
  command: "{{ macos_srvr_config_directory }}/networksetup.sh"

- name: reboot
  command: shutdown -r now
